[theme]
base="light"

[server]
headless = true

[ui]
page_title = "Minha AplicaÃ§Ã£o"  # Nome correto
page_icon = "ğŸ“Š"  # Ãcone correto

[pages]  # CorreÃ§Ã£o do caminho das pÃ¡ginas
"app.py" = "ğŸ  AplicaÃ§Ã£o"
"pages/app_explicacao.py" = "ğŸ“„ ExplicaÃ§Ã£o"
