[ui]
page_title = "Minha AplicaÃ§Ã£o"  # Nome da aba do navegador
page_icon = "ğŸ“Š"  # Ãcone opcional

[theme]
base="light"

[pages]
"app.py" = "ğŸ  AplicaÃ§Ã£o"
"pages/app_explicacao.py" = "ğŸ“– ExplicaÃ§Ã£o"
